config/routes.rb
Rails.application.routes.draw do
  root 'page#index'
  
  resources :vendeurs
  resources :categories
  resources :produits

  get 'admin' => 'admin#index'
  
  get 'store' => 'store#index', :via => :get
  match 'store/:id' => 'store#show', :as => :store_produit, :via => :get 

  get 'about' => 'page#about'
  get 'contact' => 'page#contact'
  
  devise_for :users

end

app/models/category.rb
class Category < ActiveRecord::Base

	has_many :produits #1ER type association
	validates :description, :nom, :presence => true

end

app/models/produit.rb
class Produit < ActiveRecord::Base

	belongs_to :category #2eme type d'association
	belongs_to :vendeur #2eme type d'association
	validates :description, :nom, :prix, :presence => true
	validates :prix, :numericality => true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/vendeur.rb
class Vendeur < ActiveRecord::Base
	has_one :products
	validates :pseudo, :nom, :presence => true
	
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
	before_action :authenticate_user!
  def index
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]

  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.all
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: 'Category was successfully created.' }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1
  # PATCH/PUT /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to @category, notice: 'Category was successfully updated.' }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to categories_url, notice: 'Category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def category_params
      params.require(:category).permit(:nom, :description)
    end
end

app/controllers/page_controller.rb
class PageController < ApplicationController
  def index
  end

  def about
  end

  def contact
  end
end

app/controllers/produits_controller.rb
class ProduitsController < ApplicationController
  before_action :set_produit, only: [:show, :edit, :update, :destroy]

  # GET /produits
  # GET /produits.json
  def index
    @produits = Produit.all
  end

  # GET /produits/1
  # GET /produits/1.json
  def show
  end

  # GET /produits/new
  def new
    @produit = Produit.new
    @categories = Category.order(:nom)
    @vendeurs = Vendeur.order(:pseudo)
  end

  # GET /produits/1/edit
  def edit
    @categories = Category.order(:nom)
    @vendeurs = Vendeur.order(:pseudo)
  end

  # POST /produits
  # POST /produits.json
  def create
    @produit = Produit.new(produit_params)


    respond_to do |format|
      if @produit.save
        format.html { redirect_to @produit, notice: 'Produit was successfully created.' }
        format.json { render :show, status: :created, location: @produit }
      else
        format.html { render :new }
        format.json { render json: @produit.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /produits/1
  # PATCH/PUT /produits/1.json
  def update
    respond_to do |format|
      if @produit.update(produit_params)
        format.html { redirect_to @produit, notice: 'Produit was successfully updated.' }
        format.json { render :show, status: :ok, location: @produit }
      else
        format.html { render :edit }
        format.json { render json: @produit.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /produits/1
  # DELETE /produits/1.json
  def destroy
    @produit.destroy
    respond_to do |format|
      format.html { redirect_to produits_url, notice: 'Produit was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_produit
      @produit = Produit.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def produit_params
      params.require(:produit).permit(:nom, :description, :prix, :category_id, :vendeur_id)
    end
end

app/controllers/store_controller.rb
class StoreController < ApplicationController
  def index
  	@produits = Produit.order(:nom)
  end 

  def show
  	@produit = Produit.find(params[:id])
  end
end

app/controllers/vendeurs_controller.rb
class VendeursController < ApplicationController
  before_action :set_vendeur, only: [:show, :edit, :update, :destroy]

  # GET /vendeurs
  # GET /vendeurs.json
  def index
    @vendeurs = Vendeur.all
  end

  # GET /vendeurs/1
  # GET /vendeurs/1.json
  def show
  end

  # GET /vendeurs/new
  def new
    @vendeur = Vendeur.new
  end

  # GET /vendeurs/1/edit
  def edit
  end

  # POST /vendeurs
  # POST /vendeurs.json
  def create
    @vendeur = Vendeur.new(vendeur_params)

    respond_to do |format|
      if @vendeur.save
        format.html { redirect_to @vendeur, notice: 'Vendeur was successfully created.' }
        format.json { render :show, status: :created, location: @vendeur }
      else
        format.html { render :new }
        format.json { render json: @vendeur.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /vendeurs/1
  # PATCH/PUT /vendeurs/1.json
  def update
    respond_to do |format|
      if @vendeur.update(vendeur_params)
        format.html { redirect_to @vendeur, notice: 'Vendeur was successfully updated.' }
        format.json { render :show, status: :ok, location: @vendeur }
      else
        format.html { render :edit }
        format.json { render json: @vendeur.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /vendeurs/1
  # DELETE /vendeurs/1.json
  def destroy
    @vendeur.destroy
    respond_to do |format|
      format.html { redirect_to vendeurs_url, notice: 'Vendeur was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_vendeur
      @vendeur = Vendeur.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def vendeur_params
      params.require(:vendeur).permit(:pseudo, :nom)
    end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/page_helper.rb
module PageHelper
end

app/helpers/produits_helper.rb
module ProduitsHelper
end

app/helpers/store_helper.rb
module StoreHelper
end

app/helpers/vendeurs_helper.rb
module VendeursHelper
end

app/views/admin/index.html.erb
<%= provide(:title, "Admin")%>
<div class="jumbotron">
	<p> Veuillez cliquez sur la modification que vous voulez executer : </p>
	<%= link_to 'Produit', produits_path, class: "btn btn-default"%>
	<%= link_to 'Categorie', categories_path, class: "btn btn-default"%>
	<%= link_to 'Vendeur', vendeurs_path, class: "btn btn-default"%>
</div>

 

app/views/categories/_form.html.erb
<%= form_for(@category) do |f| %>
  <% if @category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
      <% @category.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nom %><br>
    <%= f.text_field :nom %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<h1>Editing Category</h1>

<%= render 'form' %>

<%= link_to 'Show', @category %> |
<%= link_to 'Back', categories_path %>

app/views/categories/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Liste categories</h1>

<br>

<div class="container">         
  <table class="table table-striped">
    <thead>
      <tr>
        <th>Nom</th>
        <th>Description</th>
        <th colspan="3"></th>
      </tr>
    </thead>
    <tbody>
    <% @categories.each do |category| %>
      <tr>
        <td><%= category.nom %></td>
        <td><%= category.description %></td>
        <td><%= link_to 'Voir', category %></td>
        <td><%= link_to 'Modifier', edit_category_path(category) %></td>
        <td><%= link_to 'Supprimer', category, method: :delete, data: { confirm: 'Sur de supprimer ?' } %></td>
      </tr>
    <% end %>
  </tbody>
  </table>
</div>
<%= link_to 'Nouvelle catégorie', new_category_path,  class: "btn btn-default" %>
<%= link_to 'Retour', admin_path, class: "btn btn-primary" %>

app/views/categories/new.html.erb
<h1>New Category</h1>

<%= render 'form' %>

<%= link_to 'Back', categories_path %>

app/views/categories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nom:</strong>
  <%= @category.nom %>
</p>

<p>
  <strong>Description:</strong>
  <%= @category.description %>
</p>

<%= link_to 'Edit', edit_category_path(@category) %> |
<%= link_to 'Back', categories_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title> AnuLan | <%= yield(:title) %> </title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

	<%= render 'layouts/partials/nav'%>
	<div class="container", id="content">
		<%= render 'layouts/partials/flash'%>
		<%= yield %>
		<%= render 'layouts/partials/footer'%>
	</div>


</body>
</html>

app/views/layouts/partials/_flash.html.erb
<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>

app/views/layouts/partials/_footer.html.erb
<footer id='main-footer'>
	<hr> 
	<p> Anushan & Landry, &copy; 2016 All right reserved </p>
</footer>

app/views/layouts/partials/_nav.html.erb
<nav class="navbar navbar-inverse navbar-fixed-top", id="main-menu">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "AnuLan Store", root_path, class:"navbar-brand"%>
    </div>
    <div id="navbar" class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
      	<li><%= link_to "Store", store_path %></li>
        <li><%= link_to "About", about_path %></li>
         <li><%= link_to "Admin", admin_path %></li>
         <li><%= link_to "Contact", contact_path %></li>
       </ul>
    
      <ul class="nav navbar-nav navbar-right">
      <% if user_signed_in? %>
        <li><%= link_to "Log out", destroy_user_session_path, method: :delete %></li>
        <%else%>
        <li><%= link_to "Sign In", new_user_session_path %></li>
        <li><%= link_to "Sign Up", new_user_registration_path %></li>
       </ul>
      <%end%>
  </div>
</nav>

app/views/page/about.html.erb
<%= provide(:title, "About")%>
<div class="jumbotron">
<h2> A propos </h2>
<h4> Ce site est une site de vente en ligne, merci de votre visite ! </h4>
</div>

app/views/page/contact.html.erb
<%= provide(:title, "Contact")%>
<div class="jumbotron">
	<h2>Contact</h2>
	<h4>Veulliez nous contactez au 0798678712 ou bien à l'adresse mail anulanstore@yahoo.fr</h4>

</div>

app/views/page/index.html.erb
<%= provide(:title, "Home")%>
<div class="jumbotron">
	<h2 > Bienvenue sur AnuLan Store ! </h2>
	<h4> Vous trouverez ici tout ce dont vous aurez besoin! </h4>
</div>

app/views/produits/_form.html.erb
<%= form_for(@produit) do |f| %>
  <% if @produit.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@produit.errors.count, "error") %> prohibited this produit from being saved:</h2>

      <ul>
      <% @produit.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nom %><br>
    <%= f.text_field :nom %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :prix %><br>
    <%= f.text_field :prix %>
  </div>
  <div class="field">
    <%= f.label :catégorie %><br>
    <%= f.collection_select :category_id, @categories, :id, :nom %>
  </div>
  <div class="field">
    <%= f.label :vendeur %><br>
    <%= f.collection_select :vendeur_id, @vendeurs, :id, :pseudo %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/produits/_produit.html.erb
<p>  </p>
<p>  </p>
<div class="row">
  <div class="col-sm-4 col-md-3">
    <div class="thumbnail">
       <div class="caption">
         <h3><%= produit.nom%></h3>
         <p class="prix">
			 <%= number_to_currency(produit.prix,:unit=>'€')%>
		 </p>
       	 <p><a href="<%=store_produit_path(produit)%>" class="btn btn-info" role="button">Détails</a></p>
      </div>
    </div>
  </div>
</div>

app/views/produits/edit.html.erb
<h1>Editing Produit</h1>

<%= render 'form' %>

<%= link_to 'Show', @produit %> |
<%= link_to 'Back', produits_path %>

app/views/produits/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Liste produits</h1>


<br>
<table class="table table-striped">
    <thead>
      <tr>
       <th>Nom</th>
      <th>Description</th>
      <th>Prix</th>
      <th colspan="3"></th>
      </tr>
    </thead>
    <tbody>
    <% @produits.each do |produit| %>
      <tr>
        <td><%=produit.nom %></td>
        <td><%= produit.description %></td>
        <td><%= produit.prix %></td>
        <td><%= link_to 'Voir', produit %></td>
        <td><%= link_to 'Modifier', edit_produit_path(produit) %></td>
        <td><%= link_to 'Supprimer', produit, method: :delete, data: { confirm: 'Sur de vouloir supprimer?' } %>
        </td>
      </tr>
    <% end %>
  </tbody>
  </table>

<%= link_to 'Nouveau Produit', new_produit_path,  class: "btn btn-default" %>
<%= link_to 'Retour', admin_path, class: "btn btn-primary" %>

app/views/produits/new.html.erb
<h1>Nouveau produit</h1>

<%= render 'form' %>

<%= link_to 'Back', produits_path %>

app/views/produits/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nom:</strong>
  <%= @produit.nom %>
</p>

<p>
  <strong>Description:</strong>
  <%= @produit.description %>
</p>

<p>
  <strong>Prix:</strong>
  <%= @produit.prix %>
</p>

<%= link_to 'Edit', edit_produit_path(@produit) %> |
<%= link_to 'Back', produits_path %>

app/views/store/index.html.erb
<%= provide(:title, "Store")%>
<h2>Voici les <%= @produits.count %> produits disponibles actuellement.</h2>

<%= render @produits %>

app/views/store/show.html.erb
<%= provide(:title, "Store")%>
<div class="row">
  <div class="col-sm-6 col-md-4">
    <div class="thumbnail">
       <div class="caption">
         <h3><%= @produit.nom%></h3>

         <p><%=@produit.description %></p>
         
         <p class="prix">
			 <%= number_to_currency(@produit.prix,:unit=>'€')%>
		 </p>

	     <% if @produit.category %>
	       <p>
			<strong>Categorie:</strong>
	 	    <%= @produit.category.nom %>
		   </p>
		 <%end%>
		 <% if @produit.vendeur %>
	       <p>
			<strong>Vendeur:</strong>
	 	    <%= @produit.vendeur.pseudo %>
		   </p>
		 <%end%>
        
       	 <p><a href="<%=store_path%>" class="btn btn-success" role="button">Retour au store</a></p>
      </div>
    </div>
  </div>
</div>

app/views/vendeurs/_form.html.erb
<%= form_for(@vendeur) do |f| %>
  <% if @vendeur.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@vendeur.errors.count, "error") %> prohibited this vendeur from being saved:</h2>

      <ul>
      <% @vendeur.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :pseudo %><br>
    <%= f.text_field :pseudo %>
  </div>
  <div class="field">
    <%= f.label :nom %><br>
    <%= f.text_field :nom %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/vendeurs/edit.html.erb
<h1>Editing Vendeur</h1>

<%= render 'form' %>

<%= link_to 'Show', @vendeur %> |
<%= link_to 'Back', vendeurs_path %>

app/views/vendeurs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listes vendeurs</h1>

<br>

<div class="container">         
  <table class="table table-striped">
    <thead>
      <tr>
        <th>Pseudo</th>
        <th>Nom</th>
        <th colspan="3"></th>
      </tr>
    </thead>
    <tbody>
    <% @vendeurs.each do |vendeur| %>
      <tr>
        <td><%= vendeur.pseudo %></td>
        <td><%= vendeur.nom %></td>
        <td><%= link_to 'Voir', vendeur %></td>
        <td><%= link_to 'Modifier', edit_vendeur_path(vendeur) %></td>
        <td><%= link_to 'Supprimer', vendeur, method: :delete, data: { confirm: 'Sur de supprimer ?' } %></td>
      </tr>
    <% end %>
  </tbody>
  </table>
</div>


<%= link_to 'Nouveau vendeur', new_vendeur_path,  class: "btn btn-default"%>
<%= link_to 'Retour', admin_path, class: "btn btn-primary" %>

app/views/vendeurs/new.html.erb
<h1>New Vendeur</h1>

<%= render 'form' %>

<%= link_to 'Back', vendeurs_path %>

app/views/vendeurs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Pseudo:</strong>
  <%= @vendeur.pseudo %>
</p>

<p>
  <strong>Nom:</strong>
  <%= @vendeur.nom %>
</p>

<%= link_to 'Edit', edit_vendeur_path(@vendeur) %> |
<%= link_to 'Back', vendeurs_path %>